name: CI/CD Pipeline for Flask App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}   # Ensure consistency
        password: ${{ secrets.DOCKER_PASSWORD }}
          
    # Build the Docker image
    - name: Build Docker image
      run: docker build . -t ${{ secrets.DOCKER_USERNAME }}/hello-world-flaskapp:latest
      
    # Push the Docker image to Docker Hub
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/hello-world-flaskapp:latest

  deploy:
    # Deployment stage after a successful build
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    # SSH into EC2 and deploy the app using Docker Compose
    - name: Deploy to EC2 via SSH
      run: |
        ssh -o StrictHostKeyChecking=no -i "${{ secrets.EC2_KEY }}" ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} << 'EOF'
          # Pull the latest image from Docker Hub
          docker pull ${{ secrets.DOCKER_USERNAME }}/hello-world-flaskapp:latest
  
          # Run Docker Compose to recreate containers
          cd /home/ubuntu/docker
          docker-compose down
          docker-compose up -d --build
        EOF
